package bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.directwebremoting.annotations.DataTransferObject;
import org.hibernate.annotations.GenericGenerator;

import constant.Constants;


/**
 * Customer generated by hbm2java
 */
@Entity
@DataTransferObject
@Table(name = "CUSTOMER", schema = "SYSTEM")
public class Customer implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int customerid;
	private String customername;
	private String customeremail;

	public Customer() {

	}

	public Customer(int customerid, String customername) {
		this.customerid = customerid;
		this.customername = customername;
	}

	public Customer(int customerid, String customername, String customeremail) {
		this.customerid = customerid;
		this.customername = customername;
		this.customeremail = customeremail;
	}

	@Id
	@GenericGenerator(name = "sequence", strategy = "sequence", parameters = {
			@org.hibernate.annotations.Parameter(name = "sequenceName", value = "sequence"),
			@org.hibernate.annotations.Parameter(name = "allocationSize", value = "1"), })
	@GeneratedValue(generator = "sequence", strategy = GenerationType.SEQUENCE)
	@Column(name = "CUSTOMERID", unique = true, nullable = false, precision = 5, scale = 0)
	public int getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(int customerid) {
		this.customername = Constants.CUSTOMER + customerid;
		this.customeremail = customername.toLowerCase() + Constants.EMAILPOSTFIX;
		this.customerid = customerid;
	}

	@Column(name = "CUSTOMERNAME", nullable = false, length = 50)
	public String getCustomername() {
		return this.customername;
	}

	public void setCustomername(String customername) {
		this.customername = customername;
	}

	@Column(name = "CUSTOMEREMAIL", length = 50)
	public String getCustomeremail() {
		return this.customeremail;
	}

	public void setCustomeremail(String customeremail) {
		this.customeremail = customeremail;
	}

}
